### ISSUE TITLE
Update 2.0 or how to make a better skin plugin

### ISSUE THREAD

**Issue by hilltty** [TheDutchMC/SkinFixer#13]
**Sorry for not sticking to the general structure for issues, this was not possible here**

Here I would like to write what, in my opinion, can make the killer SkinRestorer and its alternatives out of this plugin

**1. Redesign the command structure**
Instead of using different commands for each function of the plugin, I suggest using one main
```
/skin (/skin help) - help command, a list of all commands and their description
/skin set <code> [slim: true/false] - installation of a skin by code
/skin add <url> - get the code from your skin
/skin reset - resetting your skin (on the skin from the Mojang account for the license, and on Steve for everyone else)
/skin version - checking plugin version
/skin reload - reload config
```
**2. Config rework**
Here I will provide my example
```yml
# SkinFixer config
# DO NOT MODIFY!
config-version: 2

# Database
# Possible options:
# - JSON (Not recommended)
# - H2
# - MYSQL
database-type: H2
sql-settings:
  table-prefix: sf_
  host: 'null'
  port: 3306
  database: 'null'
  username: 'null'
  password: 'null'

# Discord
discord-support: true
discord-settings:
  bot-token: 'null'
  channel-id: 'null'

# Language
# Possible options: EN
language: EN

# Updates
update-check: true

# Metrics
send-metrics: true
metrics-uuid: 'uuid'
```
**3. SQL support**
I already wrote this in the config, I would really like to see support for MySQL / MariaDB

**4. Ability to install skin by nickname**
I do not think this is mandatory, but for some it is important, it is worth adding the ability to install the skin by the nickname of the license account.
I think the most successful way to implement this would be through the `/skin add` command, adding the installation functionality to it both by link and by nick.

**5. Ability to restart plugin configs without stopping the server**
I don't even need to explain anything here, this is a very important and useful function.

I hope that all of the above will be implemented sometime, I really like your plugin and I am very grateful to you for your hard work.

**Thank you <3**
